// Flashcard decks and lightning-game items for Lexi's A&P Study Room.
const CARDS = [
 ["Word parts","Cardio- means…","Heart (cardiology = study of the heart)"],
 ["Word parts","Pulmo- means…","Lungs (pulmonary = about the lungs)"],
 ["Word parts","Neuro- means…","Nerves or brain"],
 ["Word parts","Derma- means…","Skin (dermatologist = skin doctor)"],
 ["Word parts","Osteo- means…","Bone (osteoporosis = weak bones)"],
 ["Word parts","Myo- means…","Muscle"],
 ["Word parts","Hema- or hemo- means…","Blood (hemoglobin, hemorrhage)"],
 ["Word parts","Gastro- means…","Stomach"],
 ["Word parts","Hepat- means…","Liver (hepatitis = inflamed liver)"],
 ["Word parts","Renal means…","About the kidneys"],
 ["Word parts","-itis means…","Inflammation (tonsillitis = inflamed tonsils)"],
 ["Word parts","-ology means…","The study of"],
 ["Word parts","Hyper- vs hypo-","Hyper = too much · Hypo = too little"],
 ["Word parts","Tachy- vs brady-","Tachy = too fast · Brady = too slow (heart rate)"],
 ["Word parts","-emia means…","In the blood (anemia, glycemia)"],
 ["Bones","The thigh bone","Femur — longest, strongest bone"],
 ["Bones","The kneecap","Patella"],
 ["Bones","The shin bone","Tibia (the big one in front)"],
 ["Bones","The upper arm bone","Humerus"],
 ["Bones","The two forearm bones","Radius (thumb side) and ulna (pinky side)"],
 ["Bones","The collarbone","Clavicle"],
 ["Bones","The shoulder blade","Scapula"],
 ["Bones","The breastbone","Sternum"],
 ["Bones","The spine bones are called…","Vertebrae"],
 ["Bones","The skull bone protecting the brain","Cranium"],
 ["Bones","The hip bones","Pelvis"],
 ["Bones","The heel bone","Calcaneus"],
 ["Muscles","The shoulder muscle (shot spot)","Deltoid"],
 ["Muscles","The front upper-arm muscle","Biceps — bends the elbow"],
 ["Muscles","The back upper-arm muscle","Triceps — straightens the elbow"],
 ["Muscles","The chest muscle","Pectoralis major (\"pecs\")"],
 ["Muscles","The front thigh muscles","Quadriceps (\"quads\") — four of them"],
 ["Muscles","The back thigh muscles","Hamstrings"],
 ["Muscles","The calf muscle","Gastrocnemius"],
 ["Muscles","The breathing muscle","Diaphragm — under the lungs"],
 ["Muscles","The buttock muscle","Gluteus maximus — the body's biggest"],
 ["Muscles","The six-pack muscle","Rectus abdominis"],
 ["Hormones & glands","Insulin comes from…","The pancreas — moves sugar from blood into cells"],
 ["Hormones & glands","Adrenaline comes from…","The adrenal glands (on top of the kidneys)"],
 ["Hormones & glands","The master gland","Pituitary — bosses the other glands"],
 ["Hormones & glands","The metabolism gland in the neck","Thyroid — sets how fast you burn energy"],
 ["Hormones & glands","The sleep hormone","Melatonin — rises when it gets dark"],
 ["Hormones & glands","Glucagon's job","Raises blood sugar (insulin's opposite)"],
 ["Hormones & glands","Main female sex hormone","Estrogen — from the ovaries"],
 ["Hormones & glands","Main male sex hormone","Testosterone — from the testes"],
 ["Hormones & glands","A hormone travels through the body in…","The blood"],
 ["Hormones & glands","Stress mode vs calm mode","Sympathetic = fight or flight · Parasympathetic = rest and digest"],
 ["Heart & blood","Blood's path: body → heart →","Lungs → heart → body (two loops!)"],
 ["Heart & blood","Arteries carry blood…","Away from the heart (A = Away)"],
 ["Heart & blood","Veins carry blood…","Back to the heart"],
 ["Heart & blood","Where oxygen is traded to cells","Capillaries — the tiniest vessels"],
 ["Heart & blood","The strongest heart chamber","Left ventricle — pumps to the whole body"],
 ["Heart & blood","The biggest artery","Aorta"],
 ["Heart & blood","Red blood cells carry…","Oxygen (using hemoglobin)"],
 ["Heart & blood","White blood cells…","Fight germs"],
 ["Heart & blood","Platelets…","Plug leaks and start clots"],
 ["Heart & blood","The liquid part of blood","Plasma"],
 ["Heart & blood","\"Lub-dub\" is the sound of…","Heart valves snapping shut"],
 ["Systems & jobs","Respiratory system's job","Bring in oxygen, breathe out carbon dioxide"],
 ["Systems & jobs","Digestive system's job","Break food down and absorb nutrients"],
 ["Systems & jobs","Urinary system's job","Filter blood, remove waste, balance water"],
 ["Systems & jobs","Nervous system's job","Carry fast messages; control everything"],
 ["Systems & jobs","Endocrine system's job","Send slower chemical messages (hormones)"],
 ["Systems & jobs","Skeletal system's job","Support, protect, store calcium, make blood cells"],
 ["Systems & jobs","Muscular system's job","Movement — of bones, food, and blood"],
 ["Systems & jobs","Integumentary system is…","The skin, hair, and nails"],
 ["Systems & jobs","Lymphatic system's job","Drain leaked fluid and fight infection"],
 ["Systems & jobs","Cardiovascular system's job","Deliver oxygen and nutrients everywhere"],
 ["Systems & jobs","Where food and air paths cross","The throat (pharynx) — the epiglottis directs traffic"],
 ["Systems & jobs","Homeostasis means…","Keeping the body's inside conditions steady"]
].map((c,i)=>({id:i,d:c[0],f:c[1],b:c[2]}));

// Lightning game: "Which body system?" Each item belongs to one system.
const GAME_SYSTEMS=["Skeletal","Muscular","Nervous","Heart & blood","Respiratory","Digestive","Urinary","Endocrine","Skin","Immune"];
const GAME_ITEMS=[
 ["Femur","Skeletal"],["Ribs","Skeletal"],["Skull","Skeletal"],["Patella (kneecap)","Skeletal"],["Vertebrae","Skeletal"],["Bone marrow","Skeletal"],
 ["Biceps","Muscular"],["Diaphragm","Muscular"],["Tendons","Muscular"],["Quadriceps","Muscular"],["Deltoid","Muscular"],
 ["Brain","Nervous"],["Spinal cord","Nervous"],["Neurons","Nervous"],["Reflexes","Nervous"],["Cerebellum","Nervous"],["Synapse","Nervous"],
 ["Aorta","Heart & blood"],["Left ventricle","Heart & blood"],["Capillaries","Heart & blood"],["Red blood cells","Heart & blood"],["Platelets","Heart & blood"],["Veins","Heart & blood"],["Hemoglobin","Heart & blood"],
 ["Lungs","Respiratory"],["Trachea (windpipe)","Respiratory"],["Alveoli","Respiratory"],["Bronchi","Respiratory"],["Voice box (larynx)","Respiratory"],
 ["Stomach","Digestive"],["Esophagus","Digestive"],["Small intestine","Digestive"],["Liver","Digestive"],["Gallbladder","Digestive"],["Saliva","Digestive"],["Large intestine","Digestive"],
 ["Kidneys","Urinary"],["Bladder","Urinary"],["Ureters","Urinary"],["Nephrons","Urinary"],["Urethra","Urinary"],
 ["Insulin","Endocrine"],["Thyroid","Endocrine"],["Pituitary gland","Endocrine"],["Adrenaline","Endocrine"],["Melatonin","Endocrine"],["Estrogen","Endocrine"],
 ["Epidermis","Skin"],["Sweat glands","Skin"],["Melanin","Skin"],["Hair follicles","Skin"],["Sebum (skin oil)","Skin"],
 ["White blood cells","Immune"],["Lymph nodes","Immune"],["Antibodies","Immune"],["Spleen","Immune"],["Fever","Immune"]
];
