const NCLEX_BANK = [
// ===== Management of Care =====
{c:"Management of Care",q:"The charge nurse is making assignments. Which client is most appropriate to assign to an LPN/LVN?",o:["A client admitted an hour ago with chest pain","A client with stable COPD receiving routine oral medications","A client who needs a unit of packed red cells started","A client awaiting discharge teaching about new insulin"],a:1,e:"LPNs care for stable clients with predictable outcomes. Initial assessment of chest pain, starting blood, and teaching all require the RN."},
{c:"Management of Care",q:"After receiving report, which client should the nurse see first?",o:["A post-op client who is suddenly restless with SpO2 88%","A client with chronic back pain rated 8/10","A client whose IV antibiotic is due in 15 minutes","A client dressed and waiting for discharge paperwork"],a:0,e:"Restlessness plus falling SpO2 is a change in oxygenation — ABCs come first. The others are stable or can wait."},
{c:"Management of Care",q:"A client who signed consent for surgery tells the nurse, \"I still don't really understand what they're going to do.\" What should the nurse do?",o:["Explain the procedure in detail","Notify the surgeon before the client goes to the OR","Reassure the client that the surgeon is very experienced","Ask the family to explain it to the client"],a:1,e:"Informed consent is the provider's responsibility; the nurse witnesses the signature. If understanding is missing, the surgeon must be notified before surgery proceeds."},
{c:"Management of Care",q:"Which task is appropriate for the nurse to delegate to unlicensed assistive personnel (UAP)?",o:["Ambulating a stable client on post-op day 2","Assessing a new client's pain","Teaching a client how to use an incentive spirometer","Checking a client's response to a new blood pressure medication"],a:0,e:"UAP may ambulate, feed, bathe, and take vitals on stable clients. Assessment, teaching, and evaluation always stay with the RN."},
{c:"Management of Care",t:"sata",q:"Which tasks may the RN delegate to unlicensed assistive personnel? Select all that apply.",o:["Recording intake and output","Taking vital signs on a stable client","Giving a bed bath","Feeding a stable client who has no swallowing problems","Teaching a client about a low-sodium diet","Performing the initial assessment on a new admission"],a:[0,1,2,3],e:"UAP can do standard, unchanging care for stable clients: I&O, vitals, hygiene, feeding. Teaching and assessment are RN-only."},
{c:"Management of Care",q:"A client with a documented do-not-resuscitate (DNR) order stops breathing. The family shouts, \"Do something!\" The nurse should:",o:["Begin CPR because the family requests it","Follow the DNR order and support the family","Call the provider to ask what to do","Ask the family to sign a new consent form"],a:1,e:"A valid DNR reflects the client's wishes and is a medical order. The nurse follows it, provides comfort, and supports the family."},
{c:"Management of Care",q:"During a mass-casualty disaster triage, which victim should be treated first?",o:["A walking victim with a broken wrist","A victim with a sucking chest wound who is breathing","A victim in cardiac arrest with fixed, dilated pupils","A victim who is anxious but uninjured"],a:1,e:"Disaster triage treats those with immediate, life-threatening injuries who are likely to survive with quick intervention. Arrest with fixed pupils is expectant; a wrist fracture can wait."},
{c:"Management of Care",q:"The nurse overhears two colleagues discussing a client's diagnosis in a public elevator. This is best described as:",o:["Acceptable if no visitors were listening","A breach of confidentiality","Allowed because both nurses are on the care team","Negligence"],a:1,e:"Discussing protected health information where others can overhear violates confidentiality (HIPAA), regardless of who was actually listening."},
{c:"Management of Care",q:"The nurse realizes a client received double the ordered dose of metoprolol. What should the nurse do first?",o:["Complete an incident report","Notify the nurse manager","Assess the client's blood pressure and heart rate","Document the error in the chart"],a:2,e:"Client safety first: assess for effects of the extra beta-blocker. Notification and the incident report come after the client is safe."},
{c:"Management of Care",q:"A provider writes an order for a dose the nurse recognizes as ten times the usual amount. The nurse should:",o:["Give the dose because the provider ordered it","Give half the ordered dose","Contact the provider to question the order before giving anything","Ask another nurse to give the medication"],a:2,e:"The nurse is legally accountable for medications given. An order that looks unsafe must be clarified with the prescriber first — never given, altered, or passed to someone else."},
{c:"Management of Care",t:"order",q:"Place the steps for taking a telephone order in the correct sequence.",o:["Write the order down exactly as the provider states it","Read the complete order back to the provider","Confirm and enter the order in the client's record","Ensure the provider countersigns within the required time"],e:"Write, read back, confirm and enter, then obtain the countersignature — read-back is the critical safety step."},
{c:"Management of Care",q:"A medical-surgical nurse is floated to the oncology unit. The best action by the nurse is to:",o:["Refuse the assignment","Accept the assignment and inform the charge nurse which oncology skills she has not performed","Care only for clients she chooses","Ask to give only medications on the new unit"],a:1,e:"A floated nurse takes the assignment but communicates limits of competence so the charge nurse can assign stable, appropriate clients."},

// ===== Safety & Infection Control =====
{c:"Safety & Infection Control",q:"A client is admitted with Clostridioides difficile infection. Which precaution is essential?",o:["Wear an N95 respirator","Wash hands with soap and water after care","Place the client with another client who has MRSA","Use alcohol-based hand rub after removing gloves"],a:1,e:"C. diff spores are not killed by alcohol rubs — soap and water plus contact precautions are required."},
{c:"Safety & Infection Control",q:"A client with suspected pulmonary tuberculosis is admitted. The nurse should place the client in:",o:["A private room with the door open","A negative-pressure room, and wear an N95 respirator","A semi-private room with another TB client, wearing a surgical mask","Standard precautions only until cultures return"],a:1,e:"TB requires airborne precautions: negative-pressure isolation and an N95 (or higher) respirator for staff."},
{c:"Safety & Infection Control",t:"sata",q:"Which interventions help prevent falls in a hospitalized older adult? Select all that apply.",o:["Keep the bed in the lowest position","Place the call light within reach","Provide non-slip footwear","Keep the path to the bathroom free of clutter","Raise all four side rails at night"],a:[0,1,2,3],e:"Low bed, call light in reach, non-slip footwear, and a clear path reduce falls. All four side rails up is a restraint and increases injury from climbing over."},
{c:"Safety & Infection Control",q:"A client in wrist restraints requires which nursing action?",o:["Tie the restraints to the side rails with a double knot","Remove the restraints and assess circulation and skin every 2 hours","Renew the restraint order once a week","Keep the restraints on until the family arrives"],a:1,e:"Restraints are tied to the bed frame with a quick-release knot, checked and released on a schedule (typically every 2 hours), and require time-limited renewable orders."},
{c:"Safety & Infection Control",t:"order",q:"A fire starts in a client's room. Place the nurse's actions in priority order (RACE).",o:["Rescue anyone in immediate danger","Activate the alarm","Confine the fire by closing doors","Extinguish the fire if it is small and safe to do so"],e:"RACE: Rescue, Alarm, Confine, Extinguish — people out first, then alarm, then contain."},
{c:"Safety & Infection Control",q:"After giving an injection, the nurse should:",o:["Recap the needle carefully using two hands","Place the uncapped needle directly into a sharps container","Break the needle before disposal","Leave the syringe on the bedside table to dispose of later"],a:1,e:"Never recap, bend, or break used needles — dispose of them immediately at the point of use in a sharps container."},
{c:"Safety & Infection Control",q:"The nurse teaches a client using home oxygen. Which statement shows understanding?",o:["\"I can smoke as long as the oxygen is set below 2 liters.\"","\"I'll keep the tank at least 10 feet from the gas stove and never smoke near it.\"","\"I'll store the tanks lying down in the closet.\"","\"Wool blankets are safest while wearing the cannula.\""],a:1,e:"Oxygen supports combustion: no smoking or open flames nearby, tanks secured upright, and avoid static-producing fabrics."},
{c:"Safety & Infection Control",q:"Which action is most important when caring for a neutropenic client?",o:["Placing fresh flowers where the client can see them","Meticulous hand hygiene before any contact","Serving fresh raw fruit with every meal","Keeping the door open for observation"],a:1,e:"Neutropenic clients need protection from organisms: hand hygiene is the single most important measure. No fresh flowers, raw produce restrictions per policy, private room."},
{c:"Safety & Infection Control",q:"Which two clients could safely share a semi-private room?",o:["A postoperative client and a client with influenza","Two clients with MRSA in the same body site","A neutropenic client and a client with pneumonia","A client with C. diff and a client with a hip replacement"],a:1,e:"Cohorting clients infected with the same organism is acceptable. Never room infectious clients with post-op or immunocompromised clients."},
{c:"Safety & Infection Control",q:"A housekeeper splashes a cleaning chemical in the eyes. The nurse's best resource for immediate treatment information is:",o:["The unit's policy binder","The product's Safety Data Sheet (SDS)","The pharmacy formulary","The house supervisor"],a:1,e:"The SDS lists the chemical's hazards and first-aid measures — flush first per SDS guidance, then follow employee-health policy."},
{c:"Safety & Infection Control",q:"A parent calls saying their toddler just swallowed several adult vitamins with iron. The nurse should tell the parent to:",o:["Give syrup of ipecac to induce vomiting","Call the Poison Control Center immediately","Give milk and watch the child overnight","Drive to the pharmacy for activated charcoal"],a:1,e:"Iron overdose is a pediatric emergency. Poison Control directs immediate management; vomiting is no longer routinely induced."},
{c:"Safety & Infection Control",t:"sata",q:"Which actions maintain a sterile field? Select all that apply.",o:["Consider the outer 1 inch of the field contaminated","Keep sterile objects above waist level","Avoid turning your back on the sterile field","Reaching over the field is acceptable if wearing sterile gloves","Discard the field if it becomes wet"],a:[0,1,2,4],e:"The 1-inch border is unsterile, keep objects above the waist and in view, and moisture wicks bacteria through (strike-through). Never reach across a sterile field."},

// ===== Health Promotion & Maintenance =====
{c:"Health Promotion & Maintenance",q:"Which vaccine should the nurse withhold from a pregnant client?",o:["Inactivated influenza","Tdap","MMR (measles, mumps, rubella)","Hepatitis B"],a:2,e:"Live vaccines like MMR and varicella are contraindicated in pregnancy. Inactivated flu and Tdap are recommended."},
{c:"Health Promotion & Maintenance",q:"The nurse teaches new parents about safe sleep. The infant should be placed:",o:["On the back, on a firm mattress with nothing else in the crib","On the stomach with a soft blanket","On the side, propped with a rolled towel","In the parents' bed for bonding"],a:0,e:"Back to sleep on a firm surface with no pillows, bumpers, or loose bedding reduces the risk of SIDS."},
{c:"Health Promotion & Maintenance",q:"Which finding in a 10-month-old should the nurse refer for further evaluation?",o:["Cannot sit without support","Says only \"mama\" and \"dada\"","Cries when the parent leaves the room","Uses a crude pincer grasp"],a:0,e:"Most infants sit unsupported by about 8 months; not sitting by 9–10 months warrants developmental evaluation. The other findings are normal."},
{c:"Health Promotion & Maintenance",q:"A 45-year-old client of average risk asks about colorectal cancer screening. The nurse responds that screening colonoscopy is recommended beginning at age:",o:["40","45","55","65"],a:1,e:"Current guidelines recommend average-risk colorectal cancer screening starting at age 45."},
{c:"Health Promotion & Maintenance",q:"A client planning pregnancy asks why folic acid matters. The best response is that adequate folic acid before conception helps prevent:",o:["Gestational diabetes","Neural tube defects","Preeclampsia","Newborn jaundice"],a:1,e:"400 mcg of folic acid daily before conception and in early pregnancy reduces neural tube defects like spina bifida."},
{c:"Health Promotion & Maintenance",q:"Which statement by a breastfeeding mother indicates the baby is getting enough milk?",o:["\"He nurses four times a day.\"","\"He has at least six wet diapers a day.\"","\"He sleeps six hours between feedings.\"","\"He spits up after most feeds.\""],a:1,e:"Six or more wet diapers a day and steady weight gain indicate adequate intake. Newborns nurse 8–12 times daily."},
{c:"Health Promotion & Maintenance",q:"A parent asks how to handle their 2-year-old's temper tantrums. The nurse's best suggestion is to:",o:["Give in quickly to stop the screaming","Ignore the tantrum while keeping the child safe","Punish the child with a long time-out","Offer candy when the tantrum starts"],a:1,e:"Tantrums are normal autonomy-seeking. Consistent limits, safety, and not reinforcing the behavior work best."},
{c:"Health Promotion & Maintenance",q:"When interviewing an adolescent during a well visit, the nurse should:",o:["Keep the parent present for all questions","Interview the adolescent alone for part of the visit","Skip questions about drugs and sex","Have the parent complete the history form"],a:1,e:"Private time with the adolescent encourages honest discussion of risk behaviors and is standard practice."},
{c:"Health Promotion & Maintenance",q:"Which immunization does the nurse recommend yearly for adults over 65?",o:["Influenza vaccine","Tetanus booster","Pneumococcal vaccine","Shingles vaccine"],a:0,e:"Influenza vaccine is yearly. Tetanus is every 10 years; pneumococcal and zoster vaccines are given per schedule, not annually."},
{c:"Health Promotion & Maintenance",t:"sata",q:"Which cardiovascular risk factors are modifiable? Select all that apply.",o:["Cigarette smoking","Sedentary lifestyle","Obesity","Family history of heart disease","Hypertension"],a:[0,1,2,4],e:"Smoking, inactivity, obesity, and blood pressure can be changed; family history and age cannot."},
{c:"Health Promotion & Maintenance",q:"A postmenopausal client asks how to protect her bones. The nurse recommends:",o:["Swimming as the main exercise","Weight-bearing exercise plus adequate calcium and vitamin D","Bed rest to avoid fractures","A low-protein diet"],a:1,e:"Weight-bearing exercise (walking, resistance training) with calcium and vitamin D slows bone loss. Swimming is not weight-bearing."},
{c:"Health Promotion & Maintenance",q:"A parent asks when their toddler can ride facing forward in the car. The best answer is:",o:["At 12 months","As soon as her legs touch the seat","When she outgrows the rear-facing seat's height or weight limit, at age 2 or older","Whenever she fusses in the car seat"],a:2,e:"Children ride rear-facing until at least age 2 or until they exceed the seat's rear-facing limits — rear-facing is significantly safer."},

// ===== Psychosocial Integrity =====
{c:"Psychosocial Integrity",q:"A client scheduled for surgery says, \"I'm afraid I won't wake up.\" The nurse's best response is:",o:["\"Don't worry — anesthesia is very safe now.\"","\"Tell me more about what's worrying you.\"","\"Your surgeon has done hundreds of these.\"","\"Would you like to talk to the chaplain?\""],a:1,e:"An open-ended invitation explores the fear. False reassurance and deflection shut the conversation down."},
{c:"Psychosocial Integrity",q:"A client with depression begins giving away treasured belongings. The nurse's priority action is to:",o:["Compliment the client's generosity","Ask directly, \"Are you thinking about killing yourself?\"","Document the behavior and continue routine care","Encourage the client to join group activities"],a:1,e:"Giving away possessions is a suicide warning sign. Asking directly about suicidal thoughts is the priority — it does not plant the idea."},
{c:"Psychosocial Integrity",q:"A client whose last drink was 12 hours ago has tremors, a pulse of 118, and is anxious. The nurse anticipates administering:",o:["Naloxone","A benzodiazepine such as lorazepam","Disulfiram","Haloperidol as first-line treatment"],a:1,e:"These are early alcohol withdrawal signs; benzodiazepines prevent progression to seizures and delirium tremens (peak risk 24–72 hours)."},
{c:"Psychosocial Integrity",q:"During a panic attack, the most helpful nursing action is to:",o:["Leave the client alone to calm down","Stay with the client and give short, simple directions in a calm voice","Explain the physiology of panic in detail","Ask the client what triggered the attack"],a:1,e:"Stay, reduce stimulation, speak calmly and simply. Teaching and exploring triggers come after the attack passes."},
{c:"Psychosocial Integrity",q:"A client with schizophrenia says, \"The voices are telling me bad things.\" The nurse's best response is:",o:["\"There are no voices — it's your imagination.\"","\"I don't hear the voices, but I can see they're frightening you. You're safe here.\"","\"Ignore them and they'll go away.\"","\"What exactly are the voices saying about me?\""],a:1,e:"Present reality without arguing, acknowledge the feeling, and assess for command hallucinations that direct harm."},
{c:"Psychosocial Integrity",q:"The spouse of a client who just died is crying quietly at the bedside. The most therapeutic nursing action is to:",o:["Explain the stages of grief","Sit quietly with the spouse and allow the tears","Say, \"He's in a better place now.\"","Leave immediately to give privacy"],a:1,e:"Therapeutic presence — staying, silence, and acceptance — supports acute grief better than platitudes or teaching."},
{c:"Psychosocial Integrity",q:"Which intervention is appropriate for a hospitalized client with anorexia nervosa?",o:["Let the client eat alone to reduce stress","Stay with the client during meals and for an hour afterward","Weigh the client only when requested","Negotiate calories at each meal"],a:1,e:"Supervision during and after meals prevents purging and hiding food. Weights are done consistently (same time, same clothing), and limits are not renegotiated meal to meal."},
{c:"Psychosocial Integrity",q:"An 80-year-old admitted with a urinary tract infection suddenly becomes confused and agitated at night. The nurse recognizes this as most likely:",o:["Early Alzheimer's disease","Delirium related to the acute infection","Normal aging","Attention-seeking behavior"],a:1,e:"Acute onset with a fluctuating course points to delirium, commonly triggered by infection in older adults. Find and treat the cause."},
{c:"Psychosocial Integrity",q:"The nurse suspects a client's injuries result from intimate partner violence. The nurse should:",o:["Ask about the injuries with the partner in the room","Interview the client alone and ask directly about safety at home","Report suspicions to the partner","Wait for the client to bring it up"],a:1,e:"Screen privately and directly, document verbatim and objectively, and help with a safety plan. Never question the client in front of the suspected abuser."},
{c:"Psychosocial Integrity",q:"A client on the behavioral unit is pacing and speaking louder and faster. The nurse should first:",o:["Call security to apply restraints","Approach calmly, use a quiet voice, and offer to talk in a low-stimulation area","Give the PRN antipsychotic immediately","Ignore the behavior"],a:1,e:"De-escalation and the least restrictive intervention always come first; restraints are a last resort."},
{c:"Psychosocial Integrity",t:"sata",q:"Which findings are consistent with opioid withdrawal? Select all that apply.",o:["Yawning and tearing eyes","Runny nose","Diarrhea and abdominal cramping","Muscle aches","Pinpoint pupils"],a:[0,1,2,3],e:"Withdrawal looks like a bad flu: yawning, lacrimation, rhinorrhea, GI upset, aches, dilated (not pinpoint) pupils. Pinpoint pupils indicate opioid intoxication."},
{c:"Psychosocial Integrity",q:"Two days after a myocardial infarction, a client insists, \"The tests are wrong — there's nothing wrong with my heart.\" The nurse identifies this defense mechanism as:",o:["Projection","Denial","Rationalization","Displacement"],a:1,e:"Refusing to accept the reality of the diagnosis is denial — common early after MI and a barrier to cardiac rehab teaching."},

// ===== Basic Care & Comfort =====
{c:"Basic Care & Comfort",q:"After a lumbar puncture, the nurse should position the client:",o:["In high Fowler's position","Flat in bed as ordered","Side-lying with the head elevated 45 degrees","In a chair for one hour"],a:1,e:"Lying flat after lumbar puncture helps prevent a post-puncture spinal headache from CSF leakage; encourage fluids."},
{c:"Basic Care & Comfort",q:"Before the first feeding through a newly inserted nasogastric tube, placement must be verified by:",o:["Auscultating injected air over the stomach","X-ray confirmation","Checking the pH of aspirate only","Asking the client to speak"],a:1,e:"X-ray is the gold standard before first use. Air auscultation is unreliable; pH testing supports ongoing checks after placement is confirmed."},
{c:"Basic Care & Comfort",q:"A client taking scheduled oxycodone should have which added to the plan of care?",o:["Fluid restriction","A scheduled stimulant laxative with fluids and fiber","Daily enemas","A low-fiber diet"],a:1,e:"Tolerance never develops to opioid constipation — start a proactive bowel regimen with fluids, fiber, activity, and a stimulant laxative."},
{c:"Basic Care & Comfort",q:"Which action helps prevent pressure injuries in an immobile client?",o:["Massage reddened bony prominences","Reposition at least every 2 hours and keep skin clean and dry","Elevate the head of the bed to 90 degrees at all times","Place a rubber ring under the sacrum"],a:1,e:"Scheduled repositioning, moisture control, and pressure redistribution prevent breakdown. Never massage reddened areas — it worsens tissue damage."},
{c:"Basic Care & Comfort",q:"The nurse teaches a client to use a cane for a weak left leg. Which instruction is correct?",o:["Hold the cane in the left hand and step with the right leg","Hold the cane in the right hand and move it forward with the left leg","Hold the cane in either hand and keep it still while walking","Hold the cane in the left hand and take small hops"],a:1,e:"The cane is held on the strong side and advances together with the weak leg, widening the base of support."},
{c:"Basic Care & Comfort",t:"sata",q:"Which suggestions help a client with insomnia? Select all that apply.",o:["Go to bed and wake at the same time every day","Avoid caffeine after mid-afternoon","Keep the bedroom cool, dark, and quiet","Watch television in bed until sleepy","Avoid long naps late in the day"],a:[0,1,2,4],e:"Consistent schedule, limiting caffeine and late naps, and a cool dark room support sleep. Screens in bed are stimulating and weaken the bed-sleep association."},
{c:"Basic Care & Comfort",q:"When feeding a client with dysphagia after a stroke, the nurse should:",o:["Offer thin liquids through a straw","Sit the client fully upright and have them tuck the chin while swallowing","Feed quickly to reduce fatigue","Lay the client at 30 degrees during meals"],a:1,e:"Upright at 90 degrees, chin tuck, slow small bites, and thickened liquids as ordered reduce aspiration. Straws and thin liquids increase risk."},
{c:"Basic Care & Comfort",q:"A client is using an ice pack for an ankle sprain. Which instruction is correct?",o:["Apply the ice directly to the skin for best effect","Apply for no more than 20–30 minutes at a time with a cloth barrier","Keep ice on continuously for the first day","Alternate ice and heat every 5 minutes"],a:1,e:"Cold is applied with a barrier for limited intervals; longer application causes reflex vasodilation and tissue injury."},
{c:"Basic Care & Comfort",q:"When caring for a client with an indwelling urinary catheter, the nurse should:",o:["Keep the drainage bag on the bed beside the client","Keep the drainage bag below the level of the bladder","Disconnect the tubing for ambulation","Loop the tubing above the bed rail"],a:1,e:"The bag stays below the bladder with tubing free of kinks and loops to prevent backflow and infection; the system stays closed."},
{c:"Basic Care & Comfort",q:"The primary reason the nurse ambulates a client the evening after abdominal surgery is to:",o:["Improve the client's appetite","Prevent complications such as DVT, ileus, and atelectasis","Reduce the need for pain medication","Save nursing time the next day"],a:1,e:"Early ambulation is the single best move against post-op clots, sluggish bowels, and lung collapse."},
{c:"Basic Care & Comfort",q:"Which nonpharmacologic strategy is most appropriate during a painful procedure on a 5-year-old?",o:["Detailed explanation of each step in medical terms","Blowing bubbles or watching a favorite video as distraction","Asking the child to lie perfectly still and quiet","Promising the child it will not hurt"],a:1,e:"Age-appropriate distraction works well for preschoolers. Never promise that something painful won't hurt — it destroys trust."},
{c:"Basic Care & Comfort",q:"The nurse teaches crutch walking on stairs. Which is correct?",o:["Going up: crutches first, then both legs","Going up: strong leg first; going down: crutches and weak leg first","Going down: strong leg first","Going up: weak leg first to strengthen it"],a:1,e:"\"Up with the good, down with the bad\" — the strong leg leads upstairs; crutches and the weak leg lead downstairs."},

// ===== Pharmacological & Parenteral Therapies =====
{c:"Pharmacological & Parenteral Therapies",q:"An order reads: potassium chloride 20 mEq IV push now. The nurse should:",o:["Give it slowly over 5 minutes","Refuse to give IV push potassium and clarify the order","Dilute it in 10 mL and push over 10 minutes","Ask another nurse to double-check the dose and give it"],a:1,e:"IV push potassium is lethal — it is always diluted and infused by pump at a controlled rate. Clarify with the prescriber."},
{c:"Pharmacological & Parenteral Therapies",q:"When mixing regular and NPH insulin in one syringe, the nurse draws up:",o:["NPH (cloudy) first, then regular (clear)","Regular (clear) first, then NPH (cloudy)","Either order, as long as the total is correct","They must never be mixed"],a:1,e:"Clear before cloudy — drawing regular first prevents contaminating the rapid-acting vial with NPH."},
{c:"Pharmacological & Parenteral Therapies",q:"A client on warfarin has an INR of 4.8. The nurse should:",o:["Give the scheduled dose","Hold the dose and notify the provider","Double the next dose","Give aspirin instead"],a:1,e:"An INR of 4.8 is above the therapeutic 2.0–3.0 range and risks bleeding; hold the warfarin and notify — vitamin K may be ordered."},
{c:"Pharmacological & Parenteral Therapies",q:"A client taking metformin is scheduled for a CT scan with IV contrast. The nurse should:",o:["Give the metformin with a sip of water before the scan","Expect the metformin to be held around the time of contrast administration","Double the dose to protect the kidneys","Give the metformin only if blood glucose is high"],a:1,e:"Metformin plus contrast in a client with renal risk can precipitate lactic acidosis; it is typically held at the time of contrast and restarted after renal function is confirmed."},
{c:"Pharmacological & Parenteral Therapies",q:"A client starting lisinopril should be taught to report which symptom immediately?",o:["A dry, tickling cough","Swelling of the lips, tongue, or face","Mild dizziness when standing quickly","Loss of appetite for a day"],a:1,e:"Facial or airway swelling is angioedema — a life-threatening ACE inhibitor reaction. The dry cough is common and annoying but not dangerous."},
{c:"Pharmacological & Parenteral Therapies",t:"sata",q:"Which findings suggest digoxin toxicity? Select all that apply.",o:["Anorexia and nausea","Seeing yellow-green halos around lights","Heart rate of 52","New confusion in an older adult","Heart rate of 88 and regular"],a:[0,1,2,3],e:"GI upset, visual halos, bradycardia, and confusion are classic toxicity signs — check the digoxin level and potassium. A regular rate of 88 is normal."},
{c:"Pharmacological & Parenteral Therapies",t:"order",q:"Ten minutes into a blood transfusion the client reports chills and low back pain. Place the nurse's actions in priority order.",o:["Stop the transfusion","Keep the IV open with normal saline using new tubing","Assess vital signs and symptoms","Notify the provider and blood bank","Return the blood bag and tubing to the blood bank"],e:"Stop the blood first, maintain access with fresh saline tubing, assess, notify, then send the unit back for analysis."},
{c:"Pharmacological & Parenteral Therapies",q:"A client receiving IV gentamicin should have which labs monitored?",o:["Liver enzymes and lipase","Serum creatinine and drug trough levels","Platelets and INR","Thyroid function tests"],a:1,e:"Aminoglycosides are nephrotoxic and ototoxic — monitor renal function, troughs, and ask about hearing changes or ringing."},
{c:"Pharmacological & Parenteral Therapies",q:"Which statement by a client with sublingual nitroglycerin indicates correct understanding?",o:["\"I'll keep the tablets in a clear plastic bag in my car.\"","\"I'll sit down, take one tablet, and call 911 if the pain isn't better in 5 minutes.\"","\"I'll swallow the tablet with a full glass of water.\"","\"A headache means I should stop taking it.\""],a:1,e:"Sit down (hypotension risk), let it dissolve under the tongue, call EMS if unrelieved after the first dose per current teaching. Store in the dark original bottle; headache is expected."},
{c:"Pharmacological & Parenteral Therapies",q:"The nurse teaches a family about a client's PCA morphine pump. Which instruction is essential?",o:["\"Press the button for her whenever she looks uncomfortable.\"","\"Only the client herself should press the button.\"","\"Press it every hour on a schedule.\"","\"The pump has no dose limits, so pressing often is fine.\""],a:1,e:"PCA-by-proxy causes overdose: a sedated client can't press the button, which is the built-in safety. Only the client doses herself."},
{c:"Pharmacological & Parenteral Therapies",q:"Two minutes after an IV antibiotic starts, the client develops hives, wheezing, and hypotension. After stopping the infusion, the nurse should prepare to give:",o:["Oral diphenhydramine","Intramuscular epinephrine","A corticosteroid inhaler","IV furosemide"],a:1,e:"This is anaphylaxis — epinephrine IM is first-line, with airway support, fluids, and antihistamines/steroids as adjuncts."},
{c:"Pharmacological & Parenteral Therapies",q:"A client starting atorvastatin should be told to report:",o:["New unexplained muscle pain or weakness","Mild nausea with the first doses","Vivid dreams","Increased appetite"],a:0,e:"Muscle pain can signal myopathy or rhabdomyolysis — the provider will check a CK level. Statins are also monitored for liver effects."},

// ===== Reduction of Risk Potential =====
{c:"Reduction of Risk Potential",q:"On post-op day 3, a client reports calf pain and the leg is warm and swollen. The nurse should:",o:["Massage the calf to relieve the cramp","Apply a sequential compression device to that leg","Keep the client in bed and notify the provider","Encourage vigorous ambulation"],a:2,e:"These findings suggest DVT. Avoid massage or compression of the affected leg (embolus risk); rest the limb and notify the provider for diagnostic workup."},
{c:"Reduction of Risk Potential",q:"Before a cardiac catheterization, which question is most important for the nurse to ask?",o:["\"When did you last eat?\"","\"Are you allergic to iodine, shellfish, or contrast dye?\"","\"Do you exercise regularly?\"","\"Have you had a cold recently?\""],a:1,e:"Contrast dye allergy can cause anaphylaxis. NPO status matters too, but the allergy history is the critical safety screen; also check kidney function and metformin use."},
{c:"Reduction of Risk Potential",q:"After a thyroidectomy, the nurse should report which finding immediately?",o:["Temperature 99.0°F","Tingling around the mouth and in the fingertips","Sore throat when swallowing","Drowsiness from anesthesia"],a:1,e:"Perioral and fingertip tingling suggests hypocalcemia from parathyroid injury — keep calcium gluconate available. Also watch for airway swelling and hoarseness."},
{c:"Reduction of Risk Potential",q:"The nurse notes continuous vigorous bubbling in the water-seal chamber of a chest tube system. This indicates:",o:["Normal functioning","An air leak in the system","The lung has fully re-expanded","The suction is set too low"],a:1,e:"Gentle tidaling with breathing is normal; continuous bubbling in the water seal means air is leaking into the system — check connections and notify if unresolved."},
{c:"Reduction of Risk Potential",q:"After a femoral cardiac catheterization, the nurse should:",o:["Ambulate the client within the first hour","Keep the affected leg straight and check the site and distal pulses frequently","Elevate the head of the bed to 90 degrees","Remove the pressure dressing after 30 minutes"],a:1,e:"Bed rest with the leg straight prevents bleeding from the arterial puncture; monitor the site for hematoma and the distal pulses for perfusion."},
{c:"Reduction of Risk Potential",q:"A client with diabetes is shaky, sweaty, and irritable. Blood glucose is 54 mg/dL. The client is alert and can swallow. The nurse should give:",o:["15 g of fast-acting carbohydrate, such as 4 oz of juice","The scheduled insulin dose with a snack","IV dextrose 50%","Glucagon IM"],a:0,e:"Conscious hypoglycemia: rule of 15 — 15 g carbs, recheck in 15 minutes, repeat if still under 70. IV dextrose and glucagon are for clients who can't swallow."},
{c:"Reduction of Risk Potential",t:"sata",q:"Which items belong at the bedside of a client with a seizure history? Select all that apply.",o:["Oral suction setup","Oxygen equipment","A padded tongue blade to insert during a seizure","Side rails padded","IV access maintained"],a:[0,1,3,4],e:"Suction, oxygen, padded rails, and IV access are standard seizure precautions. Never put anything in the mouth during a seizure."},
{c:"Reduction of Risk Potential",q:"A client reports an allergy to latex. The nurse knows the client may also react to:",o:["Bananas, avocados, and kiwi","Dairy products","Shellfish","Peanuts"],a:0,e:"Latex-fruit syndrome: banana, avocado, kiwi, and chestnut share cross-reacting proteins with latex."},
{c:"Reduction of Risk Potential",q:"Immediately before a paracentesis, the nurse should have the client:",o:["Drink two glasses of water","Empty the bladder","Lie flat for 30 minutes","Hold all medications for the day"],a:1,e:"Voiding just before the procedure keeps the bladder small and out of the needle's path."},
{c:"Reduction of Risk Potential",q:"A client receives insulin lispro at 0730 with breakfast. When is hypoglycemia most likely?",o:["Around 0830–1030","Late afternoon","At bedtime","The next morning before breakfast"],a:0,e:"Rapid-acting insulin peaks 1–3 hours after injection — watch for hypoglycemia mid-morning if intake was poor."},
{c:"Reduction of Risk Potential",q:"A post-op client coughs and the abdominal wound eviscerates. After calling for help, the nurse should:",o:["Push the organs back inside gently","Cover the organs with sterile gauze moistened with sterile saline","Apply a dry pressure dressing tightly","Give the client sips of water for comfort"],a:1,e:"Moist sterile covering protects the tissue; position low Fowler's with knees flexed, keep NPO, and prepare for surgery. Never push organs back in."},
{c:"Reduction of Risk Potential",q:"The telemetry monitor shows tall, peaked T waves in a client with kidney disease. The nurse's first action is to:",o:["Document the strip as normal for renal disease","Check the most recent potassium level and notify the provider","Give the scheduled oral potassium supplement","Encourage a banana with lunch"],a:1,e:"Peaked T waves suggest hyperkalemia, which can progress to lethal dysrhythmias — verify the level, hold potassium sources, and notify immediately."},

// ===== Physiological Adaptation =====
{c:"Physiological Adaptation",q:"A client with heart failure calls the clinic reporting a 3-pound weight gain since yesterday. The nurse should:",o:["Reassure the client this is normal fluctuation","Tell the client to report it to the provider today — it suggests fluid retention","Suggest skipping breakfast","Recommend weighing weekly instead of daily"],a:1,e:"Rapid weight gain (2–3 lb overnight or 5 lb in a week) is the earliest sign of fluid overload in heart failure and needs same-day evaluation."},
{c:"Physiological Adaptation",q:"A client with COPD is receiving oxygen. The nurse titrates to keep the SpO2 in which range?",o:["100%","88–92%","75–80%","Above 96% at all times"],a:1,e:"In COPD, an SpO2 of about 88–92% balances oxygenation against blunting the hypoxic drive and worsening CO2 retention."},
{c:"Physiological Adaptation",q:"A client with diabetic ketoacidosis has deep, rapid respirations and a fruity breath odor. The nurse understands the deep breathing is:",o:["A sign of respiratory infection","The body compensating for metabolic acidosis by blowing off CO2","Caused by anxiety","An adverse effect of insulin"],a:1,e:"Kussmaul respirations are respiratory compensation for the metabolic acidosis of DKA. Expect IV fluids first, then insulin infusion once potassium is verified."},
{c:"Physiological Adaptation",q:"A visitor's face suddenly droops on one side and her speech slurs. After activating the emergency response, the most important information for the nurse to establish is:",o:["Her blood type","The time she was last seen normal","Her insurance carrier","Her family history of stroke"],a:1,e:"Last-known-well time determines eligibility for thrombolytics. Keep her NPO until a swallow screen is done."},
{c:"Physiological Adaptation",q:"A client arrives with crushing chest pain. Which medication does the nurse anticipate giving first?",o:["Chewable aspirin","Oral acetaminophen","IV furosemide","Subcutaneous heparin"],a:0,e:"Chewed aspirin (non-enteric) rapidly inhibits platelets in suspected MI. Oxygen if hypoxic, nitroglycerin, and morphine follow per protocol."},
{c:"Physiological Adaptation",q:"A client in sickle cell vaso-occlusive crisis needs which interventions first?",o:["Cold packs and fluid restriction","IV hydration and scheduled opioid analgesia","Ambulation and deep breathing only","Iron supplements"],a:1,e:"Hydration thins sickled blood and analgesia treats severe ischemic pain; oxygen if hypoxic. Cold worsens sickling; iron is not the treatment."},
{c:"Physiological Adaptation",q:"In the first 24 hours after a major burn, the nurse evaluates fluid resuscitation as effective when:",o:["The client denies thirst","Urine output is at least 0.5 mL/kg/hr (about 30 mL/hr in an adult)","Blood pressure is 88/50","The client is sleeping comfortably"],a:1,e:"Urine output is the best bedside indicator of organ perfusion during burn resuscitation with lactated Ringer's."},
{c:"Physiological Adaptation",q:"A client with cirrhosis and ascites becomes increasingly confused. The nurse anticipates an order for:",o:["Lactulose","A high-protein shake","Diphenhydramine for sleep","Fluid bolus of normal saline"],a:0,e:"Confusion suggests hepatic encephalopathy from rising ammonia; lactulose traps and eliminates ammonia through stooling."},
{c:"Physiological Adaptation",q:"A client with acute kidney injury has a potassium of 6.8 mEq/L. The nurse's priority is to:",o:["Restrict the client's fluids","Place the client on a cardiac monitor and prepare ordered therapies to lower potassium","Give the scheduled potassium supplement","Order a high-potassium lunch tray"],a:1,e:"Potassium of 6.8 risks lethal dysrhythmias: continuous ECG monitoring, then calcium gluconate, insulin with glucose, and binders/dialysis as ordered."},
{c:"Physiological Adaptation",q:"Which finding may be the first sign of pneumonia in an 85-year-old client?",o:["High fever with shaking chills","New confusion","Sharp chest pain","Loud productive cough"],a:1,e:"Older adults often lack classic symptoms — new confusion, weakness, or falls may be the presenting sign of infection."},
{c:"Physiological Adaptation",q:"A client with Addison's disease has vomiting, hypotension, and profound weakness after missing several prednisone doses. The nurse prepares to give:",o:["IV hydrocortisone and fluids","Oral potassium","Insulin","A beta-blocker"],a:0,e:"This is addisonian crisis — replace glucocorticoids IV and restore volume immediately. Teach clients never to stop steroids abruptly."},
{c:"Physiological Adaptation",t:"sata",q:"Which findings indicate increasing intracranial pressure? Select all that apply.",o:["Decreasing level of consciousness","Widening pulse pressure","Bradycardia","Irregular respirations","Sudden hypotension with tachycardia"],a:[0,1,2,3],e:"Falling LOC is earliest; Cushing's triad (wide pulse pressure, bradycardia, irregular breathing) is late. Hypotension with tachycardia suggests shock, not ICP."}
];

const NCLEX_CASES=[
 {title:"Case: Post-op day 1 — total hip replacement",stem:"A 78-year-old client is on post-op day 1 after a right total hip replacement. She has a morphine PCA, sequential compression devices, and an abduction pillow ordered. Vital signs at 0800: BP 128/74, HR 76, RR 14, SpO2 95%.",qs:[
  {c:"Reduction of Risk Potential",q:"At 1000 the client is difficult to arouse with a respiratory rate of 7. After stopping the PCA and stimulating her, the nurse prepares to give:",o:["Flumazenil","Naloxone","Protamine sulfate","Epinephrine"],a:1,e:"Opioid-induced respiratory depression is reversed with naloxone; support breathing and keep monitoring, since naloxone wears off before morphine does."},
  {c:"Reduction of Risk Potential",q:"Which combination best prevents venous thromboembolism for this client?",o:["Bed rest and leg massage","Sequential compression devices, prescribed anticoagulant, and early ambulation","Aspirin alone once she is home","Keeping the legs dependent"],a:1,e:"Mechanical compression, pharmacologic prophylaxis (such as enoxaparin), and getting the client up early are the core of VTE prevention. Massage is contraindicated."},
  {c:"Basic Care & Comfort",q:"Which position must this client avoid?",o:["Lying supine with the abduction pillow in place","Crossing the legs and bending the hip past 90 degrees","Standing with a walker","Sitting in a raised chair"],a:1,e:"After posterior hip replacement, adduction and flexion beyond 90 degrees risk dislocating the prosthesis — no crossing legs, low chairs, or bending to tie shoes."}
 ]},
 {title:"Case: 32 weeks pregnant — preeclampsia",stem:"A client at 32 weeks gestation is admitted with preeclampsia: BP 162/110, 3+ proteinuria, brisk reflexes. A magnesium sulfate infusion is started, and calcium gluconate is placed at the bedside.",qs:[
  {c:"Pharmacological & Parenteral Therapies",q:"Which finding would make the nurse stop the magnesium infusion and call the provider?",o:["Deep tendon reflexes 2+ and present","Respiratory rate of 10 with absent patellar reflexes","Complaint of feeling warm and flushed","Urine output of 60 mL/hr"],a:1,e:"Respirations below 12, absent reflexes, or urine output under 30 mL/hr signal magnesium toxicity — stop the infusion and give calcium gluconate as ordered."},
  {c:"Physiological Adaptation",q:"Which new complaint is most concerning?",o:["Mild ankle swelling","Severe headache with visual spots and epigastric pain","Occasional Braxton Hicks contractions","Fatigue after breakfast"],a:1,e:"Headache, visual changes, and epigastric pain signal worsening severe preeclampsia and impending eclampsia or HELLP — report immediately."},
  {c:"Physiological Adaptation",q:"The client begins to seize. The nurse's first action is to:",o:["Insert a padded tongue blade","Turn the client to her side and protect her from injury","Run to get the provider","Prepare for immediate vaginal delivery"],a:1,e:"During an eclamptic seizure: side-lying position, protect from injury, maintain airway after the seizure, then assess mother and fetal heart rate."}
 ]}
];
NCLEX_CASES.forEach(cs=>cs.qs.forEach(q=>{q.stem=cs.stem; q.caseTitle=cs.title; NCLEX_BANK.push(q);}));
